### ISSUE TITLE
Not 1 selected Video starts

### ISSUE THREAD

**Issue by Draxler** [senpaiski/TopAnimeStream#12] opened 2015-02-03 17:56 UTC
I like your desktop ''streaming'' app but it doesn't want to stream videos when select it to play.
After i loged in into destop app and select (whatever) video, player open with a big play button icon in the midle. And after i click on this play button, nothing is happened. Everything stays as it is like an image. Only close (x) button works on that player.
This how it looks and i can't go forward with video after this;
![111](https://cloud.githubusercontent.com/assets/7681671/6025904/4edd967a-abd6-11e4-874f-dec6de0a63ba.PNG)

**Comment by senpaiski** [comment] 2015-02-07 19:31
Sorry for late reply, I was sick... :( Hum. Are you using Windows? and also I cannot see your username on the top left corner of your screenshot.

I was able to play the video from my account
![image](https://cloud.githubusercontent.com/assets/10069765/6093648/f9f1e0dc-aed5-11e4-824d-29980a48c282.png)

**Comment by Draxler** [comment] 2015-02-07 21:45
yes, i'm using Win OS . i coverd my username on the app ... I tryed again and again using this app time to time and i got always same issue with Play button not respoding wich means no playing videos. 
If you need any more info from me just ask. i realy like this app, the way it looks. hope i get it to work soon. :) 

Update; I copletley reinstall (uninstall and install again) this app and result is the same. Nothing happens when click on the Play button.

**Comment by senpaiski** [comment] 2015-02-08 07:21
Can you show me the console error log?

Here is how to open the console 
- Got the location folder of the application and open package.json
- Change "toolbar": false -> "toolbar": true
- Open the app 
- Click on the list button  
  ![image](https://cloud.githubusercontent.com/assets/10069765/6095728/05c0c966-af38-11e4-8da6-be73ae79e89a.png)
- The console window will appear 
- Login and go to the anime & play the video 
- Send me a screenshot of the console log  
  Ex:  
  ![image](https://cloud.githubusercontent.com/assets/10069765/6095739/09c6c550-af39-11e4-90ad-547f853ae00b.png)

**Comment by Draxler** [comment] 2015-02-08 23:39
I try to set Tollbar at ''True'' but i get this Message when i try to confirm the change. Even when i don't have nothing running or open i get this message, like this file is already running somewhere (wich Shouldn't be true). Any suggestion how to confirm ''true'' settings for toolbar or what's the problem with this message?
![222222](https://cloud.githubusercontent.com/assets/7681671/6099264/11dce1f0-aff4-11e4-8245-47e7d01bc9d7.PNG)

**Comment by senpaiski** [comment] 2015-02-09 06:10
Copy & paste the package.json on the desktop. Edit the new file & save. Copy the one from the desktop and paste it back to the application folder.

**Comment by Draxler** [comment] 2015-02-09 21:55
Thanks for suggestion how to save it;  It worked :)

Here is the consele; It said something about beiing baned ? I visit website only few times and have no problem watching video at the website.. But on desktop app can't watch from the start.. Anyway, i hope this Console would help, so i could watch on your Desktop  app as well . :)
![23](https://cloud.githubusercontent.com/assets/7681671/6116629/b032420e-b0ae-11e4-84ed-01169a407d0f.PNG)

**Comment by senpaiski** [comment] 2015-02-10 10:15
From what I can see here nothing is wrong :O 
Are you able to play the video from the direct mp4 link? (This is the last log entry.) Copy & paste the link in the browser to see if the video works. I think you will be able to play the video from the browser but not in the application maybe and it's a flash problem. I'll try to reproduce the same error on mine.

**Comment by Draxler** [comment] 2015-02-10 17:48
I have no problem playing it in the browser. Copy and paste (last entry) link as you suggested and have no proble playing it. I'm going to uniinstall anything related to flash addons and then install it again (up to date) and see if this would work.. And thank you for you assistance i realy do appreciated.
- Screenshot of playing video on browser:

![245](https://cloud.githubusercontent.com/assets/7681671/6132791/6c727d02-b155-11e4-8742-7849fccae34b.PNG)

**UPDATE ;**
You were corect. It has something to do with Flash.. I just uninstall and then install again up to date all related flash plugins and now,  IT WORKS !! Finaly :smile: 

One big Thank you for your time and help around this issue. 
Regards

**Comment by senpaiski** [comment] 2015-02-11 00:07
Really!! Good job! Let's keep this conversation for future users. One thing I want to get working is force the app to avoid using the flash player. If I can get this to work the app will be available on linux and mac :D Keep fingers crossed! xD

**Comment by Draxler** [comment] 2015-02-11 12:53
:+1:   :smile:

**Comment by Draxler** [comment] 2015-03-16 16:58
This issue happened again. When i try updated all Flash plugins over old ones (which is the step i always used for updates) it still didn't work.
I need to completley uninstall Flash player , Shock Wave player, AIR and delete all lefovers manual and then install it back latest versions, which made app working again. 
It seams this issue start reapearing whenever new update for Flash plugins come out. Usualy everything works after simple updates of Flash plugins with simple installs over old ones, without need to uninstall everything first, which is realy boring thing to do. It seams you having an issue on standby. Anyway, app is working now.

(i reopend issue, just in case but you can close it back)

**Comment by senpaiski** [comment] 2015-03-28 16:59
Hey Draxler.
It's been a while since I did not log into Github. Sorry about that. 

I wanted tell you that we won't use crappy mirrors from other providers anymore. That means that flash player will not be needed anymore and this problem will go away in the next version. I will close this issue when I release the new version. 

F.Y.I 
We will use one provider and upload our own releases. So this a big change and require a lot of time.

Thank you for using TopAnimeStream :D

**Comment by Draxler** [comment] 2015-03-29 12:38
This change would be great. i'll wait for the next relese. :)

**Comment by senpaiski** [comment] 2015-05-08 09:06
Fixed in new version. (dev branch)

**Closed as completed by senpaiski** 2015-05-08 09:06 UTC

**Comment by senpaiski** [comment] 2015-05-09 20:04
Hey Draxler. I need testers for the new upcoming version. Here is the link of the setup file https://mega.co.nz/#!rZxHgbaI!Bi6v3empFPze5cW2xUa7ezqlQhCHRyZBJfxz9OML_8k

In development

**Comment by Draxler** [comment] 2015-05-11 16:53
i'll check this out and i'll be back with some report  :smile:
